# Server
server:

  # Port
  port: 8088

  # Session
  servlet:
    session:
      timeout: 20m

# Spring
spring:
  # Profile
  profiles:
    config:
      activate:
        on-profile: prod

  # Database
  datasource:
    url:
    username:
    password:

  # Jpa
  jpa:
    open-in-view: false
    hibernate:
      # 스키마를 삭제하고 다시 생성한다.
      # ddl-auto: create
      # 스키마를 변경하지 않는다.
      # ddl-auto: none
      # 스키마를 변경된 엔티티에 맞게 업데이트한다.
      ddl-auto: update